global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'summit-agents-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 